name: jnigen_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  jnigen: ^0.2.0
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  jni: ^0.2.1
  path: ^1.8.3
