name: jnigen_example
description: A sample command-line application using jnigen.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  jni: ^0.7.2
  path: ^1.9.0

dev_dependencies:
  jnigen: ^0.7.0
  lints: ^3.0.0
  test: ^1.25.0
