// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext jni;

JniContext (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// dev.dart.Example
jclass _c_Example = NULL;

jmethodID _m_Example__ctor = NULL;
FFI_PLUGIN_EXPORT
JniResult Example__ctor() {
  load_env();
  load_class_gr(&_c_Example, "dev/dart/Example");
  if (_c_Example == NULL)
    return (JniResult){.result = {.j = 0}, .exception = check_exception()};
  load_method(_c_Example, &_m_Example__ctor, "<init>", "()V");
  if (_m_Example__ctor == NULL)
    return (JniResult){.result = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_Example, _m_Example__ctor);
  return (JniResult){.result = {.l = to_global_ref(_result)},
                     .exception = check_exception()};
}

jmethodID _m_Example__sum = NULL;
FFI_PLUGIN_EXPORT
JniResult Example__sum(int32_t a, int32_t b) {
  load_env();
  load_class_gr(&_c_Example, "dev/dart/Example");
  if (_c_Example == NULL)
    return (JniResult){.result = {.j = 0}, .exception = check_exception()};
  load_static_method(_c_Example, &_m_Example__sum, "sum", "(II)I");
  if (_m_Example__sum == NULL)
    return (JniResult){.result = {.j = 0}, .exception = check_exception()};
  int32_t _result =
      (*jniEnv)->CallStaticIntMethod(jniEnv, _c_Example, _m_Example__sum, a, b);
  return (JniResult){.result = {.i = _result}, .exception = check_exception()};
}
